fix: remove require('@actions/core')
Run actions/github-script@v6
SyntaxError: Identifier 'core' has already been declared
    at new AsyncFunction (<anonymous>)
        at callAsyncFunction
	(/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15143:16)
	    at main
	    (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15236:26)
	        at
		/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15217:1
		    at
		    /home/runner/work/_actions/actions/github-script/v6/dist/index.js:15268:3
		        at Object.<anonymous>
			(/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15271:12)
			    at Module._compile
			    (node:internal/modules/cjs/loader:1469:14)
			        at Module._extensions..js
				(node:internal/modules/cjs/loader:1548:10)
				    at Module.load
				    (node:internal/modules/cjs/loader:1288:32)
				        at Module._load
					(node:internal/modules/cjs/loader:1104:12)
					Error: Unhandled error:
					SyntaxError: Identifier 'core'
					has already been declared

Signed-off-by: LetMeFly666 <814114971@qq.com>